build-for-compare.py, patches/stripbuildinfo-with-using-ns.patch, patches/stripbuildinfo-without-using-ns.patch, patches/stripbuildinfo.patch
In the process of getting rid of `using namespace` stuff in Bitcoin Core, I ran into problems with this tool, as the patch could not be applied to the new commit. Fixing it, it would no longer work for the old commit, so a way to specify two separate patches was necessary.
This PR adds support for per-commit-hash patch filename for cases where the stripbuildinfo.patch git apply cannot be done to both commits due to changes in patch-sensitive areas in one of them. The `patches='patch1, patch2, ...'` argument is added, defaulting to `'stripbuildinfo.patch'`. Patches are expected to reside in the `patches/` folder inside `bitcoin-maintainer-tools/`.
=> Support for per-commit patch files

README.md, build-for-compare.py
Adds `--nocopy` parameter which defaults to `0` (`false`).
There is also a `--repodir` parameter, which defaults to `/tmp/repo`.
When unset, the `CWD` is `rsync`'d (or `cp`'d if no `rsync` is available) to `repodir` and all operations are then executed there, instead of in the `CWD`.
When `--nocopy` is set, things work as they have up until this point.
Also updated `README.md` to reflect new default behavior.
=> Copy repo to temp dir and perform ops there

build-for-compare.py
When comparing against the same base commit (upstream/master), it is convenient to leave tgtdir intact and to "build upon it". The problem is that the script will `exit(1)` if it runs into an existing commit dir, which 
1. means you have to explicitly remove the base commit when you are appending builds, and
2. means you do not get helpful messages about how to compare the two commits once you do so, since you then only have one commit listed.
This PR will simply skip the build process for existing commit dirs and present the helpful notices as normal. You may be forced to manually `rm -rf` the dir for a broken commitdir at times but it's worth it I think.
=> Instead of exiting, skip commits that exist in tgtdir.

README.md, clang-format.py
This archives the currently unused clang-format script from the bitcoin main repo.
=> Archive clang-format.py

patches/stripbuildinfo.patch
Update patch to reflect current Bitcoin `master`. Before this change the patch did not apply.
=> Make stripbuildinfo.patch apply cleanly against current Bitcoin master

check-dnsseeds.py
This updates the DNS seed list we're checking with the seeds currently used by Bitcoin Core.
Removes: `bitseed.xf2.org`
Adds: `seed.btc.petertodd.org`, `seed.bitcoin.sprovoost.nl`, `dnsseed.emzy.de`
=> Update DNS seed set

build-for-compare.py, patches/stripbuildinfo.patch
When doing build comparisons I'd like to be able to pass a depends prefix to `./configure`. This is not only useful for testing PRs such as https://github.com/bitcoin/bitcoin/pull/16370, but also when I don't want to install dependencies and would rather just build them using depends.
This also updates the `stripbuildinfo.patch` to apply cleanly (https://github.com/bitcoin/bitcoin/commit/25f0edd59fee454495da39c6c63f19b97cd75e96).
As well as some misc Python improvements, which can be dropped if required.
Example use:
```bash
../bitcoin-maintainer-tools/build-for-compare.py \
b7fbf74b980ebb122ae34b142f2cc49b44b92de3 \
25f0edd59fee454495da39c6c63f19b97cd75e96 \
--prefix=/bitcoin/depends/x86_64-pc-linux-gnu \
--executables=src/bitcoind,src/qt/bitcoin-qt \
--parallelism=5
```
=> Add --prefix option to build-for-compare.py for passing a depends prefix to ./configure

build-for-compare.py
Set `QT_RCC_SOURCE_DATE_OVERRIDE` to 1 in `build-for-compare.py`, so that `bitcoin-qt` builds are deterministic.
Related IRC discussion [here (line 114)](http://www.erisian.com.au/bitcoin-core-dev/log-2019-08-01.html).
=> Set QT_RCC_SOURCE_DATE_OVERRIDE so that bitcoin-qt is deterministic

github-merge.py
In the IRC meeting of today (2019-08-15) it was discussed that the github-merge tool is used by various other projects as well. For this, and other reasons (e.g. making the tool independent of any specific bitcoin release) It makes sense to move it from the bitcoin core repository (`contrib/devtools/github-merge.py`) to a more general place.
=> Add github-merge.py

README.md
This has been ported from the bitcoin/bitcoin repo, with some small changes to make it more general.
=> doc: add github-merge.py documentation

README.md, update-translations.py
As mentioned in [#16644](https://github.com/bitcoin/bitcoin/pull/16644#issuecomment-522481111), move the `update-translations.py` script out of the `bitcoin/bitcoin` repo. This script is run infrequently by maintainers, and aside from #16644, doesn't really see any changes. If it is going to be changed, it shouldn't consume review bandwidth in bitcoin/bitcoin anyways.
=> Move update-translations.py from bitcoin/bitcoin repo

github-merge.py
Fixes #30. Warn if the merge message contains an "@".
Can be tested with https://github.com/bitcoin/bitcoin/pull/16439.
```bash
merge 16439
Auto-merging test/functional/rpc_blockchain.py
Auto-merging src/rpc/util.cpp
Auto-merging src/rpc/rawtransaction.cpp
Auto-merging src/rpc/blockchain.cpp
Auto-merging src/qt/rpcconsole.cpp
Auto-merging src/bitcoin-cli.cpp
#16439 RPC: support "@height" in place of blockhash for getblock etc into master
* f4bcae95ae89cbd6512b4347bb0ba68ac8fe4d35 qt getblock %123 (Anthony Towns) (pull/16439/head)
* 817a8d2e42b521cd2910a1b0a2ab3f6e4219b831 bitcoin-cli: support "getblock %height" by doing "getblockhash height" on client side (Anthony Towns)
* c27f59ff71e2d67231631469ac88609a39d18f35 Add Type::BLOCK_REF for hash/@height (Anthony Towns)
* …
```
=> github-merge: warn if merge message contains an @

update-translations.py
This makes sure that stale translations (that have been removed on Transifex) are removed on the branch, even if the Transifex tool forgets to do so.
=> update-translations: Explicitly remove current translations

backport.py, build-for-compare.py, github-merge.py, list-pulls.py
Before (only tested github-merge):
```
[pull/17218/local-merge e3ecb347e4] Merge #17218: Replace the LogPrint function with a macro
Date: Fri Nov 1 10:08:05 2019 -0400
#17218 Replace the LogPrint function with a macro into master
* 8734c856f85cb506fa97596383dd7e7b9edd7e03 Replace the LogPrint function with a macro (Jeffrey Czyz) (pull/17218/head)
ACKs:
* I've thought about it a bit and I think for the reason I gave above I'd
want to NACK this change.
If there are motivating examples for not evaluating the calls, they should
be fixed one by one.
It would also seem like perfect forwarding and inline can help with some of
these concerns too to nudge the compiler to defer constructing strings or
whatever.
On Tue, Oct 22, 2019, 1:47 PM Jeffrey Czyz <notifications@github.com> wrote:
> *@jkczyz* …
```
=> Use str.splitlines where appropriate

README.md, make-tag.py
Add script for making release tags. Performs pre-tag checks and makes the git tag:
- Check tag syntax and validity
- Check working directory clean (no uncommitted files)
- Check autotools build system (`configure.ac`)
- IS_RELEASE is true
- Version (including RC) matches tag
- Check MSVC build system (`build_msvc/bitcoin_config.h`)
- IS_RELEASE is true
- Version matches tag
- Make the tag, automatically constructing the message and adding  `Tree-SHA512` header.
Using this consistently to make release tags will avoid issues such as forgetting to bump the RC number in the future.
=> Add script for making release tags

github-merge.py
Build a `username:review` dict rather than a list of (username, review) tuples. An older review comment should be overridden be a newer one.
Fixes: #46.
=> github-merge: filter duplicate review comments

update-translations.py
For the build system and Qt resource updates, the translation source file needs to be included, which `all_ts_files()` was ignoring earlier. This adds the option to include it if needed.
=> Allow all_ts_files() to include the translation source

optimize-pngs.py
No need to have this in the main repo, which should primarily be used to maintain the full node implementation and not helper scripts to compress image files.
=> Move optimize-pngs.py script from Bitcoin Core repo

github-merge.py
Note that this is not compatible with the Debian chroot hack for
showing the PR number but I believe users who don't use bash prefer
to use their default shell even if it does not show the PR number.
=> Drop to $SHELL instead of bash

github-merge.py
The script is supposed to print these logs inline. The default, howerver, for `git log` is to pipe them to a pager (such as `less`). This can result in horrible usability (imo) when there are a lot of commits or a small terminal is used.
Add an explicit flag `--no-pager` to prevent this from happening. If there is long output, use the scrollback feature of your terminal.
=> github-merge: Prevent git logs from being launched in pager

github-merge.py
Now that `--no-pager` is specified, no automatic newline is added by `less` anymore. Use `tformat` instead of `format` to make sure it gets added and the message about ACKs doesn't appear on the same line.
Fixes a problem in introduced in #64. I think this is the only occurrence but please check.
=> github-merge: Add missing newline

make-tag.py
Make sure that the scattered, redundant MSVC version tags are consistent too…
=> make-tag: Add check for MSVC PACKAGE_STRING, PACKAGE_VERSION

README.md, gitian-verify.py
Add a script to verify gitian signatures for a version in one glance, independent of the Ruby scripts in `gitian-builder` repository.
Example (`./gitian-verify.py -r 0.21.0rc5 -d ../gitian.sigs -k keys.txt`):
This needs a slightly different keys.txt from that on the branch (~~the key IDs must match exactly the signing keys~~, the aliases in parenthesis are important);
see this gist https://gist.github.com/laanwj/8368525bba4d89488dd5a0418884d91d
It supports these options:
```
usage: gitian-verify.py [-h] [--verbose] --release RELEASE --directory DIRECTORY --keys KEYS [--verify-program VERIFY_PROGRAM] [--compare-to COMPARE_TO]
Verify gitian signatures
optional arguments:
-h, --help            show this help message and exit
--verbose, -v         Be more verbose
--release RELEASE, -r RELEASE …
```
=> Add gitian-verify script

list-pulls.py
Replace an (inappropriate) float division by an integer division.
Change legacy formatting to f-string at the same time.
=> list-pulls: Replace float by integer division

ghwatch.py
Add issuecomment-anchors to links (when available) from `subject.latest_comment_url` in `get_html_url()`.
Closes #85.
=> ghwatch: Make links more specific

github-merge.py
This adds clarity if a repository is pushed to a new location where the numeric ids have a different meaning or are missing altogether.
=> github-merge: Always include repo_from in the merge commit message

README.md, github-merge.py
Change `--repo_from` to `--repo-from`. Kebab case is almost universally used for command-line arguments. Besides that, `-` is easier to type on most keyboards than `_`.
Also add a short option alternative, `-r`.
=> github-merge: Change --repo_from to --repo-from

README.md, gitian-verify.py
Use the 'official' Python gpg module (which interfaces to gnupg through the gpgme library instead of a subprocess) to verify detached gitian signatures.
Besides being more robust than the ad-hoc textual parser, this adds extra functionality: a separate status when a key has expired. It also avoids a potential race condition between verifying and loading the result by reading the files only once.
Often this library is already installed, at least on Debian (and part of the trusted set), so I don't think adding the extra dependency is harmful.
Edit: I think it's also slightly faster, though this script has obvious scope for parallelization. Out of scope here though.
=> gitian-verify: Switch to gpg module

gitian-verify.py
Show the builds that mismatched, with their expected and actual hashes. For example:
Only tested on top of #90.
=> gitian-verify: List mismatches

github-merge.py
Show the merge message in case there are warnings. Highlight the symbols that caused the warning.
=> github-merge: Show merge message if there are warnings

gitian-verify.py
Related to #95.
Setting the offline flag for gpgme to to disable network connections:
For the OpenPGP protocol offline mode entirely disables the use of the Dirmngr and will thus guarantee that no network connections are done as part of an operation on this context. It has only an effect with GnuPG versions 2.1.23 or later.
[Documentation Offline Mode](https://www.gnupg.org/documentation/manuals/gpgme/Offline-Mode.html)
Tested on macOS 11.3 and gpg 2.3.1.
=> gitian-verify: offline flag for gpgme to disable network connections

update-translations.py
While working on adapting the `update-translations.py` script to imported XLIFF files, I noted that strings, that are marked "translated", are, actually, untranslated, i.e., a translation is the same as a source.
This PR solves this issue.
Translation updating numbers for the recent translation state (could differs later):
- branch 0.20:
- master: -2021 / +30415 lines
- this PR: -30551 / +13642 lines
- branch 0.21:
- master: -4818 / +11815 lines
- this PR: -47035 / +10539 lines
=> Do not include actually untranslated strings into the repo

update-translations.py
It appears that conversion from XLIFF format to Qt's TS is not enough for correct update translation files in the main repo.
The problem is that the `approved` attributes of the `<trans-unit>` tags of XLIFF translation files fetched from Transifex do not follow the actual status of a messages: neither "translated:yes/no", nor "reviewed:yes/no".
Every new translatable message in the code, after `make translate` ends in the `bitcoin_en.ts` with an empty element
```
<translation type="unfinished"></translation>
```
and in  the `bitcoin_en.xlf` without `approved="yes"`.
And those attributes--`type="unfinished"` and absence of `approved="yes"`--are inherited by the fetched XLIFF translation files and the converted TS files.
Ignoring the `type="unfinished"` attribute seems the easiest way to …
=> Make update-translations.py work with XLIFF Transifex translations

README.md, backport.py
It is required because since #92 merge commit messages always include `repo_from`.
Example of usage: https://github.com/bitcoin/bitcoin/pull/22427.
=> backport.py expects pulls that are prefixed with repo name

README.md
Even though this script is specific to gitian, the rename of the directory where the keys.txt file is affects its use.
=> doc: gitian-keys is now builder-keys

github-merge.py
If there is nothing in the body of a PR, GitHub API responds with `None`. Added an `if` statement to use body as empty string if response is `None`.
Fixes https://github.com/bitcoin-core/bitcoin-maintainer-tools/issues/111
Can test this by creating a PR in some repository with no body or use this PR: https://github.com/prayank23/bitcoin/pull/6
<details>
<summary>Python code to test</summary>
```python
import codecs
import unicodedata
import re
import json
from urllib.request import Request, urlopen
def get_response(req_url, ghtoken):
req = Request(req_url)
if ghtoken is not None:
req.add_header('Authorization', 'token ' + ghtoken)
return urlopen(req)
def sanitize(s, newlines=False):
return ''.join(ch for ch in s if unicodedata.category(ch)[0] != "C" or (ch == '\n' and newlines))
def …
```
=> Use body as empty string when GitHub API responds with None

update-translations.py
We began of policy of dropping languages which are mostly untranslated. The PR that introduced this policy did not document this post-process action. This documents this policy in the section of the update-translations.py script where we state the post-processing steps that we perform.
As such, this is a follow-up to #102
=> document post-process action of dropping untranslated languages

make-tag.py
The MSVC check is no longer necessary as of bitcoin/bitcoin#23198, which generates the version information by parsing `configure.ac`.
(we likely want to backport that to 22.1 as well, to avoid needing three variants of the make-tag script)
=> make-tag: Remove MSVC check

github-merge.py
Handle deleted github users gracefully when retrieving ACKs by replacing their name with `[deleted]` in the sanitization function.
Tested with bitcoin/bitcoin#15423.
=> github-merge: Handle deleted users gracefully

README.md, update-translations.py
The old Transifex Command-Line Tool is considered deprecated (as of January 2022) and will sunset on Nov 30, 2022.
See: https://github.com/transifex/transifex-client/pull/340
A PR with accompanying changes to `.tx/config`: bitcoin/bitcoin#26321
=> Use new Transifex CLI

update-translations.py
Closes ticket [#101][0].
Ticket [#101][0] reads:
> `update-translations.py` script leaves behind `*.orig` files.
> 
> After running `python3 ../bitcoin-maintainer-tools/update-translations.py` tons of `*.orig` files remain in the repo.
> They are ignored by Git due to the `.gitignore` but they are not subjects for `make clean` or `make distclean`.
> 
> [...]
[0]: https://github.com/bitcoin-core/bitcoin-maintainer-tools/issues/101
=> Stop leaving behind `*.orig` files

github-merge.py
Avoid counting an ACK if it is in a quoted comment or with markdown indentation, when present in a review before the actual ACK. See https://github.com/bitcoin/bitcoin/pull/27334#issuecomment-1610203248 for an example.
=> github-merge: omit ACKs in quoted comments or with markdown indentation

delete_nonreduced_fuzz_inputs.sh
This is needed, because the Jammy `clang` is slowly getting outdated and lacks support for some C++20 features.
=> delete_nonreduced_fuzz_inputs.sh: Bump to Ubuntu Noble 24.04

github-merge.py
The merge script claims authorship of the merge commit, which is confusing:
* The maintainer didn't author the merged code, nor the merge commit. Everything is done by the script.
* In case of breach of a git hosting platform, such as GitHub, or the account of a maintainer, the hosting platform would allow a signed commit (signed by the hosting platform) to be pushed in the name of the maintainer. Thus, ...
* ... the important thing to check for is the commit signature or the actual code changes, not the name (or email) of the maintainer.
* Most modern software projects attribute their merges to a "merge" account, regardless of who triggered the merge. (For example, rust-lang)
Solve this issue by:
* Setting the git user name (committer and author) to "merge-script".
* (optional) Allowing …
=> github-merge: Add option to overwrite user email

github-merge.py
Fix the following warning, which appears first in Python 3.12 which became more strict about unescaped regular expressions.
```
github-merge.py:94: SyntaxWarning: invalid escape sequence '\['
```
Use a r-string instead, which was always the correct thing to do.
Check:
```
>>> assert '[a-zA-Z0-9-]+(\[bot\])?\Z' == r'[a-zA-Z0-9-]+(\[bot\])?\Z'
```
=> Fix "SyntaxWarning: invalid escape sequence"

fastcopy-chaindata.py
For long-running instances, leveldb file numbers can go on beyond 6 digits. Adapt the regexp to this.
=> fastcopy-chaindata: Leveldb file numbers can exceed 6 digits
