bitcoin-core/bitcoin-maintainer-tools

build-for-compare.py

A path is considered safe if its absolute path
1. has more than one path component (i.e. `/anything` is forbidden) and
2. resides in the `/tmp` folder.
(The commit also does some minor clean up, and sets the assertion default to the actual default rather than a hard-coded 0.)

Prompt to delete target dir if it is safe and exists.

---

README.md
backport.py

source: https://gist.github.com/laanwj/d959545e60401d82c898370f6c34b02d/revisions
Closes #11

Add backport script

---

release-prep.sh

This is a bash script which does all of the automatable stuff for release preparation as specified by the release process doc.

Release preparation script

---

unittest-statistics.py

This PR fixes issue [17](https://github.com/bitcoin-core/bitcoin-maintainer-tools/issues/17).

fixed issue that mixed up suite and test case statistics.

---

patches/stripbuildinfo.patch

Update `stripbuildinfo.patch` to make it apply cleanly against current `master`.

Update stripbuildinfo.patch to make it apply cleanly against current master

---

build-for-compare.py

Currently the script hardcodes `/tmp` as temporary directory
for building.
This is not always the correct assumption, for example this might point
to a limited in-mmemory file system in some environments, whereas
the build requires a lot of space.
Change to use `tempfile.gettempdir`. Adapt the safe path checking
to check whether inside this path.

build-for-compare: Respect TMPDIR

---

README.md
unittest-statistics.py

Also includes a commit to update the check-dnsseeds.py output in README.md.

Fixup unittest-statistics.py output

---

fastcopy-chaindata.py

Use /usr/bin/env in fastcopy-chainstate.py

---

update-translations.py

Add code to perform the steps from the build process to update git, the qt resource file, and the build system automatically.

update-translations: Perform git and build system updates

---

README.md
list-pulls.py

This is the script I've been using to generate the sorted PR list in the release notes.
So to be clear: the output of this script is a first draft based on rough heuristics, and likely needs to be extensively manually edited before ending up in the release notes.

Add list-pulls script

---

github-merge.py

Two refactoring commits and one feature commit. Fyi, my config looks like this:
```
$ git config githubmerge.pushmirrors
git@github.com:bitcoin-core/gui.git,git@github.com:MarcoFalke/bitcoin-core.git

github-merge: Add push_mirrors config setting

---

transifex-migrate-resource.py

Update transifex migration script to Python 3

---

check-dnsseeds.py

I'm assuming that maintainers are using Python 3.6+.

check-dns: add seed.testnet.bitcoin.sprovoost.nl

---

github-merge.py

Currently github-merge assumes that the fetch_repo is identical to the push_repo. This comes with several issues:
* The maintainer development fork is not updated on a merge, and the maintainer has to manually type `git push my_fork master` after each merge (if they wish so).
* github-merge is currently not suitable for a "Linux-style" monotree development style. Specifically it is not possible to merge a pull request that has been filed against a repository that is not `githubmerge.repository`.
Fix both issues by adding:
* (Done in #59) An optional push_mirrors config setting to push the master branch to more than just the main mirror. In action:
```
...
Type 's' to sign off on the above merge, or 'x' to reject and exit. s
Type 'push' to push the result to git@github.com:bitcoin/bitcoin, …
```

github-merge: Add optional support for fetch_repo != push_repo

---

github-merge.py

Remove all control characters (except for newlines in the body) from string data coming from the github API. And check the username.
Just a precaution.

github-merge: Sanitize string data coming from gh API

---

README.md
delete_nonreduced_fuzz_inputs.sh

Fixes https://github.com/bitcoin-core/qa-assets/issues/25

Add script to delete non-reduced fuzz inputs

---

README.md
ghmeta/__init__.py
ghwatch.py
termlib/attr.py
termlib/input.py
termlib/tableprinter.py

Add a script `ghwatch.py`  to watch your github notifications in the terminal. This includes, if available, metadata such as label and open/close status.
See README.md change for documentation on how to use it.
(I wasn't 100% sure whether to add this to bitcoin maintainer tools or make it a separate general tool, but as at least the label thing is entirely geared toward bitcoin maintenance right now, it seemed to make more sense to do)

Add ghwatch.py script

---

ghwatch.py
termlib/input.py

ghwatch: Adapt to terminal size changes

---

README.md
ghwatch.py

ghwatch: Auto-update metadata repositories

---

README.md
ghwatch.py

ghwatch: Notification reason priority sorting

---

ghwatch.py

While working on previous patches for ghwatch I thought that it would make sense to extract the github load from the draw function to its own. This also makes it so that there doesn't have to be a github API query on screen resizes (#82) and makes redraws less noticable (no "flickering").

ghwatch: extract github load from draw function to its own

---

gitian-verify.py

This actually implements the `--verbose` argument :-)
```
% ./gitian-verify.py -v -r 0.21.1 -d ../gitian.sigs -k ../bitcoin/contrib/gitian-keys/keys.txt
Validate linux build...
For hebasto...
gpg --quiet --batch --verify ../gitian.sigs/0.21.1-linux/hebasto/bitcoin-core-linux-0.21-build.assert.sig ../gitian.sigs/0.21.1-linux/hebasto/bitcoin-core-linux-0.21-build.assert
Status.OK
For frastefanini...
gpg --quiet --batch --verify ../gitian.sigs/0.21.1-linux/frastefanini/bitcoin-core-linux-0.21-build.assert.sig ../gitian.sigs/0.21.1-linux/frastefanini/bitcoin-core-linux-0.21-build.assert
```
It echos the `gpg --verify` command so it's easy to try it yourself. In my case this last command just got stuck.

gitian-verify: add logging for --verbose

---

make-tag-pre-22.0.py

- Update `make-tag.py` checks for post-22.x versioning scheme.
- Temporarily add `make-tag-pre-22.0.py` for older branches.

Update make-tag.py for new versioning scheme

---

list-pulls.py

This adds minimal support for handling the `bitcoin/bitcoin#1234` syntax in merge messages, as well as scaffolding for handling a project spanning multiple repositories.
We do not currently have a meta-data backup repository covering `bitcoin-core/gui` so those PRs are considered unknown but belonging to the GUI category, for now.

list-pulls.py: Minimal support for multi-repository

---

check-dnsseeds.py

- Add signet category
- Add Sjors's signet DNS seed
- Reformat DNS seed list to be better maintainable

check-dnsseeds: Add signet DNS seed

---

README.md
guix-verify.py

Added a modified gitian-verify for the new build system. Closes #129

guix-verify: Add modified gitian-verify for new build system

---

delete_nonreduced_fuzz_inputs.sh

Hopefully fixes this bug from https://github.com/bitcoin-core/qa-assets/pull/97#issuecomment-1274501233

delete_nonreduced_fuzz_inputs.sh: Add missing libsqlite3-dev

---

check-dnsseeds.py

For after https://github.com/bitcoin/bitcoin/pull/29691.

dns: update seeds from kernel/chainparams

---

delete_nonreduced_fuzz_inputs.sh

* Use llvm 18
* Minimize corpora with both afl++ and libfuzzer (#167)

delete_nonreduced_fuzz_inputs: llvm 18, afl-cmin

---

delete_nonreduced_fuzz_inputs.sh

Builds on #169.
Switch to CMake build system.

delete_nonreduced_fuzz_inputs: cmake

---

make-tag.py

Fixes https://github.com/bitcoin-core/bitcoin-maintainer-tools/issues/175.

Make `make-tag.py` compatible with CMake
